=== Limmen/WebServicesScenarios/hw1/xml/schemas/transcript.xsd
<?xml version="1.0" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.limmen.kth.se.id2208.hw1.transcript"
            xmlns="http://www.limmen.kth.se.id2208.hw1.transcript"
            elementFormDefault="qualified">

    <xsd:annotation>
        <xsd:documentation xml:lang="en">
            This Schema defines a general Transcript XML document from a University. It is linked to a particular
            student
            and lists th student's degrees and courses obtained at the university.
        </xsd:documentation>
    </xsd:annotation>

    <!-- Declares transcript element that must be present in the xml-doc -->
    <xsd:element name="Transcript" type="TranscriptType"/>


    <!-- Simple types declared separately which can allow for reuse within various elements -->
    <xsd:simpleType name="CreditsType">
        <xsd:restriction base="xsd:decimal">
            <xsd:minInclusive value="0"/>
        </xsd:restriction>
    </xsd:simpleType>

    <!-- Defines a complex type for a transcript, that can be re-used in different schemas -->
    <xsd:complexType name="TranscriptType">
        <xsd:sequence>
            <xsd:element name="Student">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="FirstName" type="xsd:string"/>
                        <xsd:element name="LastName" type="xsd:string"/>
                        <xsd:element name="CivicRegistrationNumber" type="xsd:string"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

            <xsd:element name="Degrees">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="Degree" minOccurs="0" maxOccurs="unbounded">
                            <xsd:complexType>
                                <xsd:sequence>
                                    <xsd:element name="Name" type="xsd:string"/>
                                    <xsd:element name="DateOfIssue" type="xsd:date"/>
                                    <xsd:element name="DateOfCompletion" type="xsd:date"/>
                                    <xsd:element name="Credits" type="CreditsType"/>
                                </xsd:sequence>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

            <xsd:element name="Courses">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="Course" minOccurs="0" maxOccurs="unbounded">
                            <xsd:complexType>
                                <xsd:sequence>
                                    <xsd:element name="Name" type="xsd:string"/>
                                    <xsd:element name="Code">
                                        <xsd:simpleType>
                                            <xsd:restriction base="xsd:string">
                                                <xsd:pattern value="[A-Z]{2}[0-9]{4}"/>
                                            </xsd:restriction>
                                        </xsd:simpleType>
                                    </xsd:element>
                                    <xsd:element name="Credits" type="CreditsType"/>
                                    <xsd:element name="Date" type="xsd:date"/>
                                    <xsd:element name="Grade">
                                        <xsd:simpleType>
                                            <xsd:restriction base="xsd:string">
                                                <xsd:pattern value="[A-F]"/>
                                            </xsd:restriction>
                                        </xsd:simpleType>
                                    </xsd:element>
                                </xsd:sequence>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>

        <!-- Defines attributes that can only be used within transcript elements -->
        <xsd:attribute name="universityName" type="xsd:string" use="required"/>
        <xsd:attribute name="generationDate" type="xsd:date" use="required"/>
    </xsd:complexType>

</xsd:schema>

=== Limmen/WebServicesScenarios/hw1/xml/documents/transcript.xml
<?xml version="1.0" encoding="UTF-8"?>
<Transcript
        xmlns="http://www.limmen.kth.se.id2208.hw1.transcript"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.limmen.kth.se.id2208.hw1.transcript ./../schemas/transcript.xsd"
        universityName="KTH"
        generationDate="2017-01-23">

    <Student>
        <FirstName>John</FirstName>
        <LastName>Doe</LastName>
        <CivicRegistrationNumber>910406-1337</CivicRegistrationNumber>
    </Student>

    <Degrees>
        <Degree>
            <Name>Master of Distributed Systems</Name>
            <DateOfIssue>2014-09-16</DateOfIssue>
            <DateOfCompletion>2014-06-04</DateOfCompletion>
            <Credits>180</Credits>
        </Degree>
    </Degrees>

    <Courses>
        <Course>
            <Name>Grid Computing</Name>
            <Code>IJ2208</Code>
            <Credits>7.5</Credits>
            <Date>2016-03-16</Date>
            <Grade>A</Grade>
        </Course>
        <Course>
            <Name>Distributed Systems Architecture</Name>
            <Code>IJ2213</Code>
            <Credits>7.5</Credits>
            <Date>2016-03-16</Date>
            <Grade>A</Grade>
        </Course>
    </Courses>

</Transcript>

=== Limmen/WebServicesScenarios/hw1/xml/documents/transcript_backup.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML root, xsi:schemaLocation allows to tie a document to its XML Schema by using
     schemaLocation or noNamespaceSchemaLocation. transcript is default ns -->
<tscp:Transcript
        xmlns:tscp="http://www.limmen.kth.se.id2208.hw1.transcript"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.limmen.kth.se.id2208.hw1.transcript ./../schemas/transcript.xsd"
        universityName="KTH"
        generationDate="2017-01-23">

    <tscp:Student>
        <tscp:FirstName>John</tscp:FirstName>
        <tscp:LastName>Doe</tscp:LastName>
        <tscp:CivicRegistrationNumber>910406-1337</tscp:CivicRegistrationNumber>
    </tscp:Student>

    <tscp:Degrees>
        <tscp:Degree>
            <tscp:Name>Master of Distributed Systems</tscp:Name>
            <tscp:DateOfIssue>2014-09-16</tscp:DateOfIssue>
            <tscp:DateOfCompletion>2014-06-04</tscp:DateOfCompletion>
            <tscp:Credits>180</tscp:Credits>
        </tscp:Degree>
    </tscp:Degrees>

    <tscp:Courses>
        <tscp:Course>
            <tscp:Name>Grid Computing</tscp:Name>
            <tscp:Code>IJ2208</tscp:Code>
            <tscp:Credits>7.5</tscp:Credits>
            <tscp:Date>2016-03-16</tscp:Date>
            <tscp:Grade>A</tscp:Grade>
        </tscp:Course>
        <tscp:Course>
            <tscp:Name>Distributed Systems Architecture</tscp:Name>
            <tscp:Code>IJ2213</tscp:Code>
            <tscp:Credits>7.5</tscp:Credits>
            <tscp:Date>2016-03-16</tscp:Date>
            <tscp:Grade>A</tscp:Grade>
        </tscp:Course>
    </tscp:Courses>

</tscp:Transcript>
