=== Limmen/WebServicesScenarios/hw1/src/main/java/limmen/kth/se/id2208/hw1/java_mappings/generated_pojos/short_cv/short_cv.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.limmen.kth.se.id2208.hw1.short_cv"
            xmlns="http://www.limmen.kth.se.id2208.hw1.short_cv"
            elementFormDefault="qualified">

    <xsd:annotation>
        <xsd:documentation xml:lang="en">
            This schema defines a short CV for a job-seeker. It contains personal information, skills, degrees and
            previous working experience.
        </xsd:documentation>
    </xsd:annotation>

    <!-- Global main element ShortCV -->
    <xsd:element name="ShortCV">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="PersonalInformation">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="FirstName">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:minLength value="1"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:element name="LastName">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:minLength value="1"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:element name="City" type="xsd:string"/>
                            <xsd:element name="CivicRegistrationNumber">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:pattern value="\d{6}-\d{4}"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:element name="Email">
                                <!-- RegEx for valid email retreived from: http://www.zvon.org/xxl/XMLSchemaTutorial/Output/ser_types_st4.html -->
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:pattern value="[^@]+@[^\.]+\..+"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="Skills">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Skill" type="xsd:string" minOccurs="0" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="Preferences">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="JobInterest" type="xsd:string"/>
                            <xsd:element name="JobType">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:enumeration value="permanent"/>
                                        <xsd:enumeration value="part time"/>
                                        <xsd:enumeration value="contract"/>
                                        <xsd:enumeration value="consult"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:element name="Locations">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="Location" type="xsd:string" maxOccurs="unbounded"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="MotivationLetter" type="xsd:string"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== Limmen/WebServicesScenarios/hw1/xml/documents/short_cv.xml
<?xml version="1.0" encoding="utf-8" ?>
<ShortCV xmlns="http://www.limmen.kth.se.id2208.hw1.short_cv"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.limmen.kth.se.id2208.hw1.short_cv ./../schemas/short_cv.xsd">
    <PersonalInformation>
        <FirstName>John</FirstName>
        <LastName>Doe</LastName>
        <City>Stockholm</City>
        <CivicRegistrationNumber>910406-1337</CivicRegistrationNumber>
        <Email>johndoe@kth.se</Email>
    </PersonalInformation>
    <Skills>
        <Skill>XML</Skill>
        <Skill>Web Services</Skill>
        <Skill>Semantic Web</Skill>
    </Skills>
    <Preferences>
        <JobInterest>Looking for job opportunities within the field of Web Services</JobInterest>
        <JobType>permanent</JobType>
        <Locations>
            <Location>Stockholm</Location>
            <Location>Uppsala</Location>
            <Location>Södertälje</Location>
        </Locations>
    </Preferences>
    <MotivationLetter>I'm very passionate about Web Services and I read XML before bed</MotivationLetter>
</ShortCV>
