=== Limmen/WebServicesScenarios/hw1/src/main/java/limmen/kth/se/id2208/hw1/parsing/generated_pojos/company_info/company_info.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.limmen.kth.se.id2208.hw1.company_info"
            xmlns="http://www.limmen.kth.se.id2208.hw1.company_info"
            elementFormDefault="qualified">

    <xsd:annotation>
        <xsd:documentation xml:lang="en">
            This Schema defines a Companies Information XML document. The Company Information provides general
            information
            about companies.
        </xsd:documentation>
    </xsd:annotation>

    <!-- Global main element CompaniesInfo -->
    <xsd:element name="CompaniesInfo">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Company" minOccurs="0" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Name">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:minLength value="1"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:element name="Address" type="xsd:string"/>
                            <xsd:element name="Anno" type="xsd:gYear"/>
                            <xsd:element name="About" type="xsd:string"/>
                            <xsd:element name="Contact">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="Phone" minOccurs="0">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:string">
                                                    <!-- RegEx for international phone number validation from: http://www.regexlib.com/Search.aspx?k=phone&AspxAutoDetectCookieSupport=1 -->
                                                    <xsd:pattern
                                                            value="^(\+[1-9][0-9]*(\([0-9]*\)|-[0-9]*-))?[0]?[1-9][0-9\- ]*$"/>
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>
                                        <xsd:element name="Email">
                                            <!-- RegEx for valid email retreived from: http://www.zvon.org/xxl/XMLSchemaTutorial/Output/ser_types_st4.html -->
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:string">
                                                    <xsd:pattern value="[^@]+@[^\.]+\..+"/>
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                            <xsd:element name="Website" type="xsd:string"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== Limmen/WebServicesScenarios/hw1/xml/documents/company_info.xml
<CompaniesInfo xmlns="http://www.limmen.kth.se.id2208.hw1.company_info"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.limmen.kth.se.id2208.hw1.company_info  ./../schemas/company_info.xsd">
    <Company>
        <Name>SOAP Solutions</Name>
        <Address>Ärvingevägen 14</Address>
        <Anno>2008</Anno>
        <About>We provide complete web services solutions. SOAP Solutions at your service</About>
        <Contact>
            <Phone>070-1111111</Phone>
            <Email>contact@soap_solutions.com</Email>
        </Contact>
        <Website>soap_solutions.com</Website>
    </Company>
    <Company>
        <Name>FIFAA</Name>
        <Address>Qatar</Address>
        <Anno>2008</Anno>
        <About>Fotball association authority</About>
        <Contact>
            <Email>contact@fifaa.com</Email>
        </Contact>
        <Website>fifaaa.com</Website>
    </Company>
</CompaniesInfo>
