=== Limmen/WebServicesScenarios/hw1/src/main/java/limmen/kth/se/id2208/hw1/parsing/generated_pojos/employment_record/employment_record.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.limmen.kth.se.id2208.hw1.employment_record"
            xmlns="http://www.limmen.kth.se.id2208.hw1.employment_record"
            elementFormDefault="qualified">

    <xsd:annotation>
        <xsd:documentation xml:lang="en">
            This Schema defines a Employment Record XML document. The employment record presents previous employments.
        </xsd:documentation>
    </xsd:annotation>

    <!-- Global main element EmploymentRecord -->
    <xsd:element name="EmploymentRecord">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="Employee">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="FirstName">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:minLength value="1"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:element name="LastName">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:minLength value="1"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:element name="CivicRegistrationNumber">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:pattern value="\d{6}-\d{4}"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:element name="Email">
                                <!-- RegEx for valid email retreived from: http://www.zvon.org/xxl/XMLSchemaTutorial/Output/ser_types_st4.html -->
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:pattern value="[^@]+@[^\.]+\..+"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="EmploymentHistory">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Employment" minOccurs="0" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="StartDate" type="xsd:date"/>
                                        <xsd:element name="EndDate" type="xsd:date"/>
                                        <xsd:element name="Company">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:string">
                                                    <xsd:minLength value="1"/>
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>
                                        <xsd:element name="Title" type="xsd:string"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== Limmen/WebServicesScenarios/hw1/xml/documents/employment_record.xml
<EmploymentRecord xmlns="http://www.limmen.kth.se.id2208.hw1.employment_record"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://www.limmen.kth.se.id2208.hw1.employment_record  ./../schemas/employment_record.xsd">
    <Employee>
        <FirstName>John</FirstName>
        <LastName>Doe</LastName>
        <CivicRegistrationNumber>910406-1337</CivicRegistrationNumber>
        <Email>johdoe@kth.se</Email>
    </Employee>
    <EmploymentHistory>
        <Employment>
            <StartDate>2013-01-07</StartDate>
            <EndDate>2015-02-03</EndDate>
            <Company>SOAP Solutions</Company>
            <Title>Software Engineer</Title>
        </Employment>
    </EmploymentHistory>
</EmploymentRecord>
