=== Limmen/WebServicesScenarios/hw1/src/main/java/limmen/kth/se/id2208/hw1/parsing/generated_pojos/application_profile/application_profile.xsd
<?xml version="1.0" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.limmen.kth.se.id2208.hw1.application_profile"
            xmlns="http://www.limmen.kth.se.id2208.hw1.application_profile"
            elementFormDefault="qualified">


    <xsd:annotation>
        <xsd:documentation xml:lang="en">
            This Schema defines a Application Profile XML document. The Application Profile represents a job-seeker,
        </xsd:documentation>
    </xsd:annotation>

    <!-- Global main element ApplicationProfile -->
    <xsd:element name="ApplicationProfile">
        <xsd:complexType>
            <xsd:sequence>
                <!-- General Person information, can be collected from short_cv, transcript or employment_record-->
                <xsd:element name="Person">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="FirstName">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:minLength value="1"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:element name="LastName">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:minLength value="1"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:element name="CivicRegistrationNumber">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:pattern value="\d{6}-\d{4}"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

                <!-- Job preferences, collected from short_cv-->
                <xsd:element name="Preferences">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="JobInterest" type="xsd:string"/>
                            <xsd:element name="JobType">
                                <xsd:simpleType>
                                    <xsd:restriction base="xsd:string">
                                        <xsd:enumeration value="permanent"/>
                                        <xsd:enumeration value="part time"/>
                                        <xsd:enumeration value="contract"/>
                                        <xsd:enumeration value="consult"/>
                                    </xsd:restriction>
                                </xsd:simpleType>
                            </xsd:element>
                            <xsd:element name="Locations">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="Location" type="xsd:string" maxOccurs="unbounded"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

                <!-- Motivation letter, collected from short_cv -->
                <xsd:element name="MotivationLetter" type="xsd:string"/>

                <!-- Degrees, collected from transcript -->
                <xsd:element name="Degrees">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Degree" minOccurs="0" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="Name">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:string">
                                                    <xsd:minLength value="1"/>
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>
                                        <xsd:element name="DateOfCompletion" type="xsd:date"/>
                                        <xsd:element name="Credits">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:float">
                                                    <xsd:minInclusive value="0"/>
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>
                                        <xsd:element name="GPA">
                                            <xsd:simpleType>
                                                <xsd:restriction base="xsd:float">
                                                    <xsd:minInclusive value="0"/>
                                                    <xsd:maxInclusive value="5"/>
                                                </xsd:restriction>
                                            </xsd:simpleType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>

                <!-- Working experience, collected from employment record and company_info-->
                <xsd:element name="WorkingExperience">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Employment" minOccurs="0" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <xsd:element name="StartDate" type="xsd:date"/>
                                        <xsd:element name="EndDate" type="xsd:date"/>
                                        <xsd:element name="Company">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="Name">
                                                        <xsd:simpleType>
                                                            <xsd:restriction base="xsd:string">
                                                                <xsd:minLength value="1"/>
                                                            </xsd:restriction>
                                                        </xsd:simpleType>
                                                    </xsd:element>
                                                    <xsd:element name="About" type="xsd:string"/>
                                                    <xsd:element name="Website" type="xsd:string"/>
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                        <xsd:element name="Title" type="xsd:string"/>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== Limmen/WebServicesScenarios/hw1/xml/documents/application_profile.xml
<ApplicationProfile xmlns="http://www.limmen.kth.se.id2208.hw1.application_profile"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://www.limmen.kth.se.id2208.hw1.application_profile   ./../schemas/application_profile.xsd">
    <Person>
        <FirstName>John</FirstName>
        <LastName>Doe</LastName>
        <CivicRegistrationNumber>910406-1337</CivicRegistrationNumber>
    </Person>
    <Preferences>
        <JobInterest>Looking for job opportunities within the field of Web Services</JobInterest>
        <JobType>permanent</JobType>
        <Locations>
            <Location>Stockholm</Location>
            <Location>Uppsala</Location>
            <Location>Södertälje</Location>
        </Locations>
    </Preferences>
    <MotivationLetter>I'm very passionate about Web Services and I read XML before bed</MotivationLetter>
    <Degrees>
        <Degree>
            <Name>Master of Distributed Systems</Name>
            <DateOfCompletion>2014-06-04</DateOfCompletion>
            <Credits>180</Credits>
            <GPA>5</GPA>
        </Degree>
    </Degrees>
    <WorkingExperience>
        <Employment>
            <StartDate>2013-01-07</StartDate>
            <EndDate>2015-02-03</EndDate>
            <Company>
                <Name>SOAP Solutions</Name>
                <About>We provide complete web services solutions. SOAP Solutions at your service</About>
                <Website>soap_solutions.com</Website>
            </Company>
            <Title>Software Engineer</Title>
        </Employment>
    </WorkingExperience>
</ApplicationProfile>
